//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayByBank.Pokemon.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pokemon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pokemon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayByBank.Pokemon.Common.Resources.Pokemon", typeof(Pokemon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;base_happiness&quot;:70,&quot;capture_rate&quot;:190,&quot;color&quot;:{&quot;name&quot;:&quot;yellow&quot;,&quot;url&quot;:&quot;https://pokeapi.co/api/v2/pokemon-color/10/&quot;},&quot;egg_groups&quot;:[{&quot;name&quot;:&quot;ground&quot;,&quot;url&quot;:&quot;https://pokeapi.co/api/v2/egg-group/5/&quot;},{&quot;name&quot;:&quot;fairy&quot;,&quot;url&quot;:&quot;https://pokeapi.co/api/v2/egg-group/6/&quot;}],&quot;evolution_chain&quot;:{&quot;url&quot;:&quot;https://pokeapi.co/api/v2/evolution-chain/10/&quot;},&quot;evolves_from_species&quot;:{&quot;name&quot;:&quot;pichu&quot;,&quot;url&quot;:&quot;https://pokeapi.co/api/v2/pokemon-species/172/&quot;},&quot;flavor_text_entries&quot;:[{&quot;flavor_text&quot;:&quot;最近發表了聚集大量皮卡丘\n來建造發電廠的計畫。&quot;,&quot;language&quot;:{&quot;nam [rest of string was truncated]&quot;;.
        /// </summary>
        public static string pikachu {
            get {
                return ResourceManager.GetString("pikachu", resourceCulture);
            }
        }
    }
}
